import type {
  GameEndReason,
  MatchRecord,
  PaginatedResponse,
  RankingEntry,
} from '@/types/game';
import { DEFAULT_GAME_CONFIG } from '@/config/gameConfig';

/** Typed contract shared by the Axios client, the MSW handlers and the tests. */
export type MatchConfig = MatchRecord['config'];

/**
 * The two player-facing knobs that decide which matches are comparable:
 * ranking only puts next to each other matches with the same configuration.
 */
export function matchConfigKey(config: MatchConfig): string {
  return `${config.sessionTimeSeconds}:${config.enemySpawn.intervalMs}`;
}

/** Rebuilds a full config from those two knobs (query params or options). */
export function matchConfigFrom(
  sessionTimeSeconds: number,
  spawnIntervalMs: number
): MatchConfig {
  const seconds =
    Number.isFinite(sessionTimeSeconds) && sessionTimeSeconds > 0
      ? sessionTimeSeconds
      : DEFAULT_GAME_CONFIG.sessionTimeSeconds;
  const interval =
    Number.isFinite(spawnIntervalMs) && spawnIntervalMs > 0
      ? spawnIntervalMs
      : DEFAULT_GAME_CONFIG.enemySpawn.intervalMs;
  return {
    sessionTimeSeconds: seconds,
    enemySpawn: { ...DEFAULT_GAME_CONFIG.enemySpawn, intervalMs: interval },
  };
}

export const PAGE_SIZE = 5;

/**
 * Deterministic order for the leaderboard: score descending, oldest match
 * first on ties, then id — so equal scores never reshuffle between reloads.
 */
export function compareRankingEntries(a: RankingEntry, b: RankingEntry): number {
  if (b.score !== a.score) return b.score - a.score;
  if (a.date !== b.date) return a.date < b.date ? -1 : 1;
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

/** History reads newest first, id as the stable tie-break. */
export function compareHistoryRecords(a: MatchRecord, b: MatchRecord): number {
  if (a.date !== b.date) return a.date < b.date ? 1 : -1;
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

export type RankingParams = {
  sessionTimeSeconds: number;
  spawnIntervalMs: number;
  page: number;
  limit: number;
};

export type HistoryParams = {
  playerId: string;
  page: number;
  limit: number;
};

/**
 * `id` is generated by the client when the match ends and doubles as the
 * idempotency key: sending the same match again returns the stored record.
 */
export type RegisterMatchBody = {
  id: string;
  playerId: string;
  playerName: string;
  date: string;
  score: number;
  durationMs: number;
  endReason: GameEndReason;
  config: MatchConfig;
};

export type RegisterMatchResponse = {
  record: MatchRecord;
  rankingEntry: RankingEntry;
  duplicate: boolean;
};

export type ApiErrorBody = { message: string };

export type RankingResponse = PaginatedResponse<RankingEntry>;
export type HistoryResponse = PaginatedResponse<MatchRecord>;

export type RegistrationState = {
  state: 'pending' | 'recorded' | 'failed';
  message: string;
};
